SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE '/home/mathew/Sem4/DBMS-LAB/SQL/data/Department.csv'
INTO TABLE Department FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/mathew/Sem4/DBMS-LAB/SQL/data/Faculty.csv'
INTO TABLE Faculty FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/mathew/Sem4/DBMS-LAB/SQL/data/Student.csv'
INTO TABLE Student FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/mathew/Sem4/DBMS-LAB/SQL/data/Course.csv'
INTO TABLE Course FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE '/home/mathew/Sem4/DBMS-LAB/SQL/data/Enrollment.csv'
INTO TABLE Enrollment FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n' IGNORE 1 ROWS;

SET FOREIGN_KEY_CHECKS = 1;
